package br.com.rfloja.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// Import das classes para trabalhar com o preenchimento do endereço a partir do CEP
import br.com.rfloja.controller.FabricanteController;
import br.com.rfloja.controller.PcController;
import br.com.rfloja.model.Fabricante;
import br.com.rfloja.model.PcTableModel;
import br.com.rfloja.model.TableColumnAdjuster;
import br.com.rfloja.model.Pc;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

// Import de componentes da interface gráfica
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Rodrigo Fereira Rodrigues
 */
public class PcView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientesPFView
     */
    public PcView() {
        initComponents();
        jTablePc.setModel(tableModel);

        preencheComboBox();
        preencheTabela();

        //ajustaTabela();
        habilitaCampos(false);
        habilitaBotoes(false);
    }

    //Instancia minha jTable com base no modelo de Tabela definido no pacote MODEL
    PcTableModel tableModel = new PcTableModel();

    public void preencheTabela() {

        tableModel.limpaTabela();
        Pc pc = new Pc();
        PcController fabCtrl = new PcController();
        for (Pc fab : fabCtrl.readPc()) {
            tableModel.addRow(fab);
        }
        jTablePc.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTablePc);
        tca.adjustColumns();

    }

    public JTextField[] limparCampos() {
        JTextField[] campos = {jTextFieldModelo, jTextFieldPreco, jTextFieldCod};
        for (int i = 0; i < campos.length; i++) {
            campos[i].setText("");
        }
        return campos;
    }

    public boolean verificaCamposEmBranco() {
        int erros = 0;
        String cepvazio = "     -   ";
        String telvazio = "(  )       -     ";
        JTextField[] campos = {jTextFieldModelo, jTextFieldPreco};
        String[] camposNome = {"Pc", "Obs"};
        for (int i = 0; i < campos.length; i++) {
            if (campos[i].getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Campo " + camposNome[i] + " em branco, verifique");
                erros++;
            }
        }
        if (erros == 0) {
            return true;
        } else {
            return false;
        }
    }

    private void habilitaCampos(boolean estado) {

        jTextFieldModelo.setEnabled(estado);
        jTextFieldPreco.setEnabled(estado);
    }

    private void habilitaBotoes(boolean estado) {
        jButtonAlterar.setEnabled(estado);
        jButtonCancelar.setEnabled(estado);
        jButtonExcluir.setEnabled(estado);
        jButtonLimpar.setEnabled(estado);
        jButtonSalvar.setEnabled(estado);
        jButtonVerificaPendencias.setEnabled(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDadosFabricantes = new javax.swing.JPanel();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jTextFieldCod = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jComboBoxCodFabricantes = new javax.swing.JComboBox<>();
        jLabelCodFabricante = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldVelocidadeGhz = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTamanhoRam = new javax.swing.JTextField();
        jTextFieldTamanhoHd = new javax.swing.JTextField();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePc = new javax.swing.JTable();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonConsulta = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVerificaPendencias = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonFecharJanela = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(787, 412));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanelDadosFabricantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        jPanelDadosFabricantes.setPreferredSize(new java.awt.Dimension(787, 412));

        jTextFieldModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldModeloFocusLost(evt);
            }
        });

        jTextFieldPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoActionPerformed(evt);
            }
        });

        jTextFieldCod.setEditable(false);

        jLabelCPF.setText("Modelo:");

        jLabelNome.setText("Preço:");

        jLabelId.setText("Cód:");

        jComboBoxCodFabricantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cod Fabricante" }));

        jLabelCodFabricante.setText("----");

        jLabel1.setText("Velocidade:");

        jLabel2.setText("Tamanho RAM:");

        jLabel3.setText("Tamanho HD");

        javax.swing.GroupLayout jPanelDadosFabricantesLayout = new javax.swing.GroupLayout(jPanelDadosFabricantes);
        jPanelDadosFabricantes.setLayout(jPanelDadosFabricantesLayout);
        jPanelDadosFabricantesLayout.setHorizontalGroup(
            jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosFabricantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosFabricantesLayout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNome))
                    .addGroup(jPanelDadosFabricantesLayout.createSequentialGroup()
                        .addComponent(jComboBoxCodFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabelCodFabricante)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTamanhoRam, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosFabricantesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldVelocidadeGhz, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosFabricantesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTamanhoHd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        jPanelDadosFabricantesLayout.setVerticalGroup(
            jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosFabricantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPF)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldVelocidadeGhz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCodFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodFabricante)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTamanhoRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTamanhoHd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Clientes Pessoa Física"));

        jTablePc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "HP", "2,3", "8", "500", "2000", "1"}
            },
            new String [] {
                "Cód", "Modelo", "Velocidade Ghz", "Tamanho Ram", "Tamanho HD", "Preço", "Cód Fabricante"
            }
        ));
        jTablePc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePcMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTablePcMouseReleased(evt);
            }
        });
        jTablePc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTablePcKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePc);

        javax.swing.GroupLayout jPanelTabelaLayout = new javax.swing.GroupLayout(jPanelTabela);
        jPanelTabela.setLayout(jPanelTabelaLayout);
        jPanelTabelaLayout.setHorizontalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelTabelaLayout.setVerticalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonConsulta.setText("Consultar");
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar Campos");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVerificaPendencias.setText("Verifica Pendências");
        jButtonVerificaPendencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificaPendenciasActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonFecharJanela.setText("Fechar");
        jButtonFecharJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharJanelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerificaPendencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFecharJanela)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAlterar)
                        .addComponent(jButtonLimpar)
                        .addComponent(jButtonSalvar)
                        .addComponent(jButtonFecharJanela)
                        .addComponent(jButtonExcluir)
                        .addComponent(jButtonVerificaPendencias))
                    .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovo)
                        .addComponent(jButtonCancelar))
                    .addComponent(jButtonConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDadosFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDadosFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jPanelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelTabela.getAccessibleContext().setAccessibleName("Dados Pessoais");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTablePc.getSelectedRow() != -1) {
            PcController fabCtrl = new PcController();
            Pc pc = new Pc();
            pc.setCod(Integer.parseInt(jTextFieldCod.getText()));
            pc.setModelo(jTextFieldModelo.getText());
            pc.setVelocidadeGhz(Float.parseFloat(jTextFieldVelocidadeGhz.getText()));
            pc.setTamanhoRAM(Integer.parseInt(jTextFieldTamanhoRam.getText()));
            pc.setTamanhoHD(Integer.parseInt(jTextFieldTamanhoHd.getText()));
            pc.setPreco(Integer.parseInt(jTextFieldPreco.getText()));
            pc.setCodFabricante(Integer.parseInt(jComboBoxCodFabricantes.getSelectedItem().toString()));
            if (fabCtrl.deletePc(pc)) {
                JOptionPane.showMessageDialog(this, "Pc deletado com sucesso");
                preencheTabela();
                limparCampos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Pc para deletar");
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaActionPerformed
        // Acessando direto pelo Controller
        preencheTabela();
        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Banco de dados vazio");
        }
    }//GEN-LAST:event_jButtonConsultaActionPerformed

    private void jTextFieldPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // Limpa os campos
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        PcController fabCtrl = new PcController();
        Pc pc = new Pc();
        pc.setModelo(jTextFieldModelo.getText());
        pc.setVelocidadeGhz(Float.parseFloat(jTextFieldVelocidadeGhz.getText()));
        pc.setTamanhoRAM(Integer.parseInt(jTextFieldTamanhoRam.getText()));
        pc.setTamanhoHD(Integer.parseInt(jTextFieldTamanhoHd.getText()));
        pc.setPreco(Integer.parseInt(jTextFieldPreco.getText()));
        pc.setCodFabricante(Integer.parseInt(jComboBoxCodFabricantes.getSelectedItem().toString()));
        if (fabCtrl.createPc(pc)) {
            JOptionPane.showMessageDialog(this, "Salvo com sucesso");
            preencheTabela();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        if (jTablePc.getSelectedRow() != -1) {
            PcController fabCtrl = new PcController();
            Pc pc = new Pc();
            pc.setCod(Integer.parseInt(jTextFieldCod.getText()));
            pc.setModelo(jTextFieldModelo.getText());
            pc.setVelocidadeGhz(Float.parseFloat(jTextFieldVelocidadeGhz.getText()));
            pc.setTamanhoRAM(Integer.parseInt(jTextFieldTamanhoRam.getText()));
            pc.setTamanhoHD(Integer.parseInt(jTextFieldTamanhoHd.getText()));
            pc.setPreco(Integer.parseInt(jTextFieldPreco.getText()));
            pc.setCodFabricante(Integer.parseInt(jComboBoxCodFabricantes.getSelectedItem().toString()));
            if (fabCtrl.updatePc(pc)) {
                JOptionPane.showMessageDialog(this, "Pc Alterado com sucesso");
                preencheTabela();
                limparCampos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Pc para alterar");
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        habilitaCampos(true);
        habilitaBotoes(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        habilitaBotoes(false);
        habilitaCampos(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTablePcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePcMouseClicked
        // TODO add your handling code here:
        if (jTablePc.getSelectedRow() != -1) {
            jTextFieldCod.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 0).toString());
            jTextFieldModelo.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 1).toString());
            jTextFieldVelocidadeGhz.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 2).toString());
            jTextFieldTamanhoRam.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 3).toString());
            jTextFieldTamanhoHd.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 4).toString());
            jTextFieldPreco.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 2).toString());
            jComboBoxCodFabricantes.setSelectedItem(jTablePc.getValueAt(jTablePc.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_jTablePcMouseClicked

    private void jTablePcMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePcMouseReleased
        // TODO add your handling code here:
        if (jTablePc.getSelectedRow() != -1) {
            jTextFieldCod.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 0).toString());
            jTextFieldModelo.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 1).toString());
            jTextFieldVelocidadeGhz.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 2).toString());
            jTextFieldTamanhoRam.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 3).toString());
            jTextFieldTamanhoHd.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 4).toString());
            jTextFieldPreco.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 2).toString());
            jComboBoxCodFabricantes.setSelectedItem(jTablePc.getValueAt(jTablePc.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_jTablePcMouseReleased

    private void jTablePcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePcKeyReleased
        // TODO add your handling code here:
        if (jTablePc.getSelectedRow() != -1) {
            jTextFieldCod.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 0).toString());
            jTextFieldModelo.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 1).toString());
            jTextFieldVelocidadeGhz.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 2).toString());
            jTextFieldTamanhoRam.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 3).toString());
            jTextFieldTamanhoHd.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 4).toString());
            jTextFieldPreco.setText(jTablePc.getValueAt(jTablePc.getSelectedRow(), 2).toString());
            jComboBoxCodFabricantes.setSelectedItem(jTablePc.getValueAt(jTablePc.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_jTablePcKeyReleased

    private void jTextFieldModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldModeloFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextFieldModeloFocusLost

    private void jButtonVerificaPendenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificaPendenciasActionPerformed
        // TODO add your handling code here:
        if (verificaCamposEmBranco()) {
            JOptionPane.showMessageDialog(this, "Nenhuma Pendência encontrada");
        }
    }//GEN-LAST:event_jButtonVerificaPendenciasActionPerformed

    private void jButtonFecharJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharJanelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharJanelaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFecharJanela;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVerificaPendencias;
    private javax.swing.JComboBox<String> jComboBoxCodFabricantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCodFabricante;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelDadosFabricantes;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePc;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldTamanhoHd;
    private javax.swing.JTextField jTextFieldTamanhoRam;
    private javax.swing.JTextField jTextFieldVelocidadeGhz;
    // End of variables declaration//GEN-END:variables

    private void preencheComboBox() {
        FabricanteController fabCtrl = new FabricanteController();
        ArrayList<Fabricante> listaFabricantes = fabCtrl.readFabricante();
        ArrayList<String> listaCodFabricante = new ArrayList<>();
        for (Fabricante listaFabricante : listaFabricantes) {
            listaCodFabricante.add("" + listaFabricante.getCod());
        }
        DefaultComboBoxModel defaultComboBoxFabricante = new DefaultComboBoxModel(listaCodFabricante.toArray());
        jComboBoxCodFabricantes.setModel(defaultComboBoxFabricante);

    }
}
